USE GUESTBOOK;

DROP TABLE IF EXISTS GMUSER;
#게임계정
CREATE TABLE GMUSER
(
    ID_GMUSER INT NOT NULL auto_increment PRIMARY KEY, #계정IDX(PK)
    USER_ID   VARCHAR(30)  NOT NULL,                    #계정ID(UK1) 
    USER_PWD  VARCHAR(200) NOT NULL,                    #계정비밀번호(sha)
    USERNAME  VARCHAR(30)  NULL                         #성명
);
ALTER TABLE GMUSER
ADD CONSTRAINT UK1_GMUSER UNIQUE(USER_ID);


INSERT INTO GMUSER(USER_ID,USER_PWD,USERNAME)VALUES('junios',sha('1234'),'강희운');
INSERT INTO GMUSER(USER_ID,USER_PWD,USERNAME)VALUES('wjlee',sha('5678'),'이웅재');

SELECT * FROM GMUSER;
SELECT COUNT(1) FROM GMUSER WHERE USER_ID = 'wjlee';




