USE GUESTBOOK;

select * from gmuser;

CALL SPC_UPSERT_GMUSER('wjlee','5678');



DROP PROCEDURE IF EXISTS `SPC_UPSERT_GMUSER`
DELIMITER $$
CREATE PROCEDURE `SPC_UPSERT_GMUSER`
(
	IN IN_USER_ID VARCHAR(30),
    IN IN_USER_PWD VARCHAR(30)
)
BEGIN
	DECLARE ISEXISTS INT;
	SET ISEXISTS = (SELECT COUNT(1) FROM GMUSER WHERE USER_ID = IN_USER_ID);
    
	IF(ISEXISTS) THEN
		UPDATE GMUSER SET
			USER_PWD = IN_USER_PWD
		WHERE USER_ID = IN_USER_ID;
	ELSE
		INSERT INTO GMUSER
		(
			USER_ID,
			USER_PWD
		)VALUES(
			IN_USER_ID,
			IN_USER_PWD
		);
	END IF;
END $$
DELIMITER ;



