USE GUESTBOOK;

DELIMITER $$
DROP PROCEDURE IF EXISTS `UPSERT_GMUSER`
(
	IN IN_USER_ID VARCHAR(30),
    IN IN_USER_PWD VARCHAR(30)
)
BEGIN
	IF(EXISTS(SELECT COUNT(1) FROM GMUSER WHERE USER_ID = IN_USER_ID)) BEGIN
		UPDATE GMUSER SET
			USER_PWD = IN_USER_PWD
		WHERE USER_ID = IN_USER_ID
	END
	ELSE BEGIN
		INSERT INTO GMUSER
		(
			USER_ID,
			USER_PWD
		)VALUES(
			IN_USER_ID,
			IN_USER_PWD
		);
	END
END $$
DELIMITER ;


DROP PROCEDURE IF EXISTS SELECT_GMUSER
	@USER_ID VARCHAR(30) NOT NULL,
	@USER_PWD VARCHAR(30) NOT NULL
BEGIN
	SELECT 
		*
	FROM GMUSER
	WHERE 
		USER_ID = USER_ID AND 
		USER_PWD = ISNULL(USER_PWD, '');
END

